config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  resources :users do
    member do
      get  'video_chat'
      get 'android_video'
      get  'secret_word'
      patch 'secret_word_update'
    end
  end

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save { self.email = email.downcase }
  attr_accessor :remember_token
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = "ログインしました。"
      if user.admin?
        redirect_to users_url
      else
        redirect_back_or user
      end
    else
      flash.now[:danger] = 'メールアドレスとパスワードの組み合わせは有効ではありません'
      render 'new'
    end
  end
  
  def destroy
    log_out
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :video_chat, :secret_word, :secret_word_update, :update, :destroy]
  before_action :logged_in_user, only: [:show, :index, :video_chat, :secret_word, :secret_word_update, :edit, :update, :destroy]
  before_action :correct_user, only: :update
  before_action :admin_or_correct_user, only: [:edit, :update, :video_chat]
  before_action :admin_user, only: [:secret_word, :secret_word_update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザー情報を登録しました。"
      redirect_to @user
    else
      render :new
    end
  end

  def index
    @users = User.where(admin: false).paginate(page: params[:page])
  end


  def show
  end

  def video_chat
  end

  def secret_word
  end

  def android_video
  end

  def secret_word_update
    @admin = User.find_by(admin: true)
    if @user.update_attributes(secret_params)
      flash[:success] = "ユーザに合言葉を送信しました。"
      NotificationMailer.secret_mail(@user, @admin).deliver if current_user.email.present?
    else
      flash[:danger] = "送信できませんでした。"
    end
    redirect_to users_url
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def secret_params
      params.require(:user).permit(:secret_word)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:danger] = "アクセス権限がありません。"
        redirect_to(root_url)
      end
    end

    def admin_user
      unless current_user.admin?
        flash[:danger] = "アクセス権限がありません"
        redirect_to(root_url)
      end
    end

    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "アクセス権限がありません。"
        redirect_to(root_url)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_name = "")
    base_title = "Online_Visit_App"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget 
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end
  
  def redirect_back_or(default_url)
    redirect_to(session[:forwarding_url] || default_url)
    session.delete(:forwarding_url)
  end
  
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_chats_helper.rb
module VideoChatsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <strong><%= link_to 'Online_Visit_App', root_path, class: "navbar-brand" %></strong>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
      
  <div class="collapse navbar-collapse" id="Navber">
    <ul class="navbar-nav mr-auto"> 
    </ul>
    <ul class="navbar-nav mr-auto"> 
    </ul>
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <% unless current_user.admin? %>
          <li class="nav-item">
            <%= link_to "予約する", '#', class: "nav-link" %>
          </li>&emsp;
        <% end %>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>&emsp;
        <% end %>
        <li class="nav-item">
          <%= link_to "Video_Chat", video_chat_user_path(current_user), class: "nav-link" %>
        </li>&emsp;
        <li class="dropdown nav-item">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "編集", edit_user_path(current_user), class: "nav-link" %>
            </li>
            <li class="divider"></li>
            <li class="nav-item">
              <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ログイン", login_path, class: "nav-link" %>
        </li>&emsp;
        <li class="nav-item">
          <%= link_to "新規登録", new_user_path, class: "nav-link" %>
        </li>&emsp;
      <% end %>   
    </ul>  
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.webrtc.ecl.ntt.com/skyway-latest.js"></script>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       入力エラーが<%= obj.errors.count %>件ありました。
    </div>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/top.html.erb
<% provide(:title, "Top") %>
<ul class="image-top"></ul>

<div class="text-center jumbotron" id="image-background">
  <h1>Online_Visit</h1>
  <p>このアプリケーションでは、オンラインで入居者と家族を結ぶシステムとなります。</p>
  <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" unless logged_in? %>
</div>

app/views/users/_secret_word.html.erb
<% provide(:class_text, 'secret-word') %>

<div class="modal-dialog modal-lg modal-dialog-center" role="document">
  <div class="modal-content">
    <div class="modal-header alert-info">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <h1 class="modal-title text-center">Video_Chat_password</h1>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 mx-auto">
          <%= form_with(model: @user, url: secret_word_update_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', obj: @user %>
            
            <%= f.label :secret_word, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :secret_word, class: "form-control" %>
            <div class="center">
              <%= f.submit "送信する", class: "btn btn-info btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-outline-secondary btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/android_video.html.erb
<button type="button" onclick="startVideo();">Start video</button>
<button type="button" onclick="stopVideo();">Stop video</button>
&nbsp;&nbsp;&nbsp;&nbsp;
<button type="button" onclick="connect();">Connect</button>
<button type="button" onclick="hangUp();">Hang Up</button>
<br />
<div>
  <video id="local-video" autoplay style="width: 240px; height: 180px; border: 1px solid black;"></video>
  <video id="remote-video" autoplay style="width: 240px; height: 180px; border: 1px solid black;"></video>
  </div>

  <p>
    SDP to send:<br />
    <textarea id="text-for-send-sdp" rows="5" cols="100" disabled="1">SDP to send</textarea>
  </p>
  <p>
    SDP to receive:<br />
    <textarea id="text-for-receive-sdp" rows="5" cols="100"></textarea><br />
    <button type="button" onclick="onSDP();">Receive SDP</button>
  </p>

  <p>
    ICE Candidate to send:<br />
    <textarea id="text-for-send-ice" rows="5" cols="100" disabled="1">ICE Candidate to send</textarea>
  </p>
  <p>
    ICE Candidates to receive:<br />
    <textarea id="text-for-receive-ice" rows="5" cols="100"></textarea><br />
    <button type="button" onclick="onICE();">Receive ICE Candidates</button>
  </p>


  <script>
  var localVideo = document.getElementById('local-video');
  var remoteVideo = document.getElementById('remote-video');
  var localStream = null;
  var peerConnection = null;
  var peerStarted = false;
  var mediaConstraints = {'mandatory': {'OfferToReceiveAudio':true, 'OfferToReceiveVideo':true }};

  // ----------------- handshake --------------
  var textForSendSDP = document.getElementById('text-for-send-sdp');
  var textForSendICE = document.getElementById('text-for-send-ice');
  var textToReceiveSDP = document.getElementById('text-for-receive-sdp');
  var textToReceiveICE = document.getElementById('text-for-receive-ice');
  var iceSeparator = '------ ICE Candidate -------';
  var CR = String.fromCharCode(13);

  function onSDP() {
    var text = textToReceiveSDP.value;
	var evt = JSON.parse(text);
	if (peerConnection) {
	  onAnswer(evt);
	}
	else {
	  onOffer(evt);
	}

	textToReceiveSDP.value ="";
  }

  //--- multi ICE candidate ---
  function onICE() {
    var text = textToReceiveICE.value;
	var arr = text.split(iceSeparator);
	for (var i = 1, len = arr.length; i < len; i++) {
      var evt = JSON.parse(arr[i]);
	  onCandidate(evt);
    }

	textToReceiveICE.value ="";
  }


  function onOffer(evt) {
    console.log("Received offer...")
	console.log(evt);
    setOffer(evt);
	sendAnswer(evt);
  }

  function onAnswer(evt) {
    console.log("Received Answer...")
	console.log(evt);
	setAnswer(evt);
  }

  function onCandidate(evt) {
    var candidate = new RTCIceCandidate({sdpMLineIndex:evt.sdpMLineIndex, sdpMid:evt.sdpMid, candidate:evt.candidate});
    console.log("Received Candidate...")
	console.log(candidate);
    peerConnection.addIceCandidate(candidate);
  }

  function sendSDP(sdp) {
    var text = JSON.stringify(sdp);
	console.log("---sending sdp text ---");
	console.log(text);

	textForSendSDP.value = text;
  }

  function sendCandidate(candidate) {
    var text = JSON.stringify(candidate);
	console.log("---sending candidate text ---");
	console.log(text);

	textForSendICE.value = (textForSendICE.value + CR + iceSeparator + CR + text + CR);
	textForSendICE.scrollTop = textForSendICE.scrollHeight;
  }

  // ---------------------- video handling -----------------------
  // start local video
  function startVideo() {
    navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: true },
    function (stream) { // success
      localStream = stream;
      localvideo.srcObject = localStream;
      localVideo.playsInline = true;
      localVideo.muted = true;
      localVideo.play();
    },
    function (error) { // error
      console.error('An error occurred: [CODE ' + error.code + ']');
      return;
    }
	);
  }

  // stop local video
  function stopVideo() {
    localVideo.srcObject = null;
    localStream.stop();
  }

  // ---------------------- connection handling -----------------------
  function prepareNewConnection() {
    var pc_config = {"iceServers":[]};
    var peer = null;
    try {
      peer = new webkitRTCPeerConnection(pc_config);
    } catch (e) {
      console.log("Failed to create peerConnection, exception: " + e.message);
    }

    // send any ice candidates to the other peer
    peer.onicecandidate = function (evt) {
      if (evt.candidate) {
        console.log(evt.candidate);
        sendCandidate({type: "candidate",
                          sdpMLineIndex: evt.candidate.sdpMLineIndex,
                          sdpMid: evt.candidate.sdpMid,
                          candidate: evt.candidate.candidate}
		);
      } else {
        console.log("End of candidates. ------------------- phase=" + evt.eventPhase);
      }
    };

    console.log('Adding local stream...');
    peer.addStream(localStream);

    peer.addEventListener("addstream", onRemoteStreamAdded, false);
    peer.addEventListener("removestream", onRemoteStreamRemoved, false)

    // when remote adds a stream, hand it on to the local video element
    function onRemoteStreamAdded(event) {
      console.log("Added remote stream");
      remoteVideo.src = window.webkitURL.createObjectURL(event.stream);
    }

    // when remote removes a stream, remove it from the local video element
    function onRemoteStreamRemoved(event) {
      console.log("Remove remote stream");
      remoteVideo.src = "";
    }

    return peer;
  }

  function sendOffer() {
    peerConnection = prepareNewConnection();
    peerConnection.createOffer(function (sessionDescription) { // in case of success
      peerConnection.setLocalDescription(sessionDescription);
      console.log("Sending: SDP");
      console.log(sessionDescription);
      sendSDP(sessionDescription);
    }, function () { // in case of error
      console.log("Create Offer failed");
    }, mediaConstraints);
  }

  function setOffer(evt) {
    if (peerConnection) {
	  console.error('peerConnection alreay exist!');
	}
    peerConnection = prepareNewConnection();
    peerConnection.setRemoteDescription(new RTCSessionDescription(evt));
  }

  function sendAnswer(evt) {
    console.log('sending Answer. Creating remote session description...' );
	if (! peerConnection) {
	  console.error('peerConnection NOT exist!');
	  return;
	}

    peerConnection.createAnswer(function (sessionDescription) { // in case of success
      peerConnection.setLocalDescription(sessionDescription);
      console.log("Sending: SDP");
      console.log(sessionDescription);
      sendSDP(sessionDescription);
    }, function () { // in case of error
      console.log("Create Answer failed");
    }, mediaConstraints);
  }

  function setAnswer(evt) {
    if (! peerConnection) {
	  console.error('peerConnection NOT exist!');
	  return;
	}
	peerConnection.setRemoteDescription(new RTCSessionDescription(evt));
  }

  // -------- handling user UI event -----
  // start the connection upon user request
  function connect() {
    //if (!peerStarted && localStream && channelReady) {
	if (!peerStarted && localStream) {
      sendOffer();
      peerStarted = true;
    } else {
      alert("Local stream not running yet - try again.");
    }
  }

  // stop the connection upon user request
  function hangUp() {
    console.log("Hang up.");
    stop();
  }

  function stop() {
    peerConnection.close();
    peerConnection = null;
    peerStarted = false;
  }
</script>

app/views/users/index.html.erb
<% provide(:title, 'index') %>

<div class="col-12">
  <%= will_paginate(@users, class: "pagination justify-content-center",
                          renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  <div class="mx-auto text-center"><h1>ユーザー一覧</h1></div><br>
  <table class="table" id="table-users">
    <thead class="thead-dark">
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th>編集</th>
        <th>削除</th>
        <th>Room Nameの設定</th>
        <th>Room Name</th>
        <th>Video_Chat</th>
        <th>Android_chat</th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= link_to "編集", edit_user_path(user), class: "btn btn-success" %></td>
        <td>
          <%= link_to "削除", user, method: :delete,
            data: { confirm: "削除してよろしいですか？" },
            class: "btn btn-danger" %>
        </td>
        <td>
          <%= link_to "Video_Chat_password", secret_word_user_path(user), remote: true, class: "btn btn-info" %>
        </td>
        <td>
          <%= user.secret_word %>
        </td>
        <td>
          <%= link_to "Video_Chat", video_chat_user_path(user), class: "btn btn-warning" %>
        </td>
        <td>
          <%= link_to "Android_chat",  android_video_user_path(user), class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </table><br>
  <div class="text-center">
    <%= link_to "マイページ", user_path(current_user), class: "btn btn-lg btn-primary" %>
  </div>

  <%= will_paginate(@users, class: "pagination justify-content-center",
                          renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

<div id="secret-word" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>

<ul class="image-top"></ul>

<div class="jumbotron" id="image-user">
  <h1 class="text-center">新規作成</h1>
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages', obj: @user %>
        
        <%= f.label :name, class: "label-signup" %>
        <%= f.text_field :name, class: "form-control" %>
          
        <%= f.label :email, class: "label-signup" %>
        <%= f.email_field :email, class: "form-control" %>
          
        <%= f.label :password, class: "label-signup" %>
        <%= f.password_field :password, class: "form-control" %>
          
        <%= f.label :password_confirmation, class: "label-signup" %>
        <%= f.password_field :password_confirmation, class: "form-control" %><br>
          
        <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/secret_word.js.erb
$("#secret-word").html("<%= escape_javascript(render 'secret_word') %>");
$("#secret-word").modal("show");

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="jumbotron">
  <h1 class="text-center">マイページ</h1><br>
  <div class="text-center"><%= link_to "Video_Chat", video_chat_user_path(@user), class: "btn btn-lg btn-warning" %></div>
</div>

    
    

app/views/users/video_chat.html.erb
<% provide(:title, 'video_chat') %>

<div class="container">
  <div class="col-12">
    <div class="mx-auto text-center"><h1>Video_Chat_Room</h1>
      <p class="note">
        Change Room mode (before join in a room):
        <a href="#">mesh</a> / <a href="#sfu">sfu</a>
      </p>
      <div class="room">
        <div>
          <video id="js-local-stream"></video>
          <span id="js-room-mode"></span>:
          <input type="text" placeholder="Room Nameを入力" value="<%= @user.secret_word %>" id="js-room-id">
          <button id="js-join-trigger">入室</button>
          <button id="js-leave-trigger">退室</button>
        </div>

        <div class="remote-streams" id="js-remote-streams"></div><br>
        <h3><strong>Room Name:&emsp;<font color="bule"><%= @user.secret_word %></font></strong></h3>
        <div>
          <pre class="messages" id="js-messages"></pre>
          <input type="text" id="js-local-text">
          <button id="js-send-trigger">送る</button>
        </div>
      </div>
      <p class="meta" id="js-meta"></p>
    </div>
    <% if current_user.admin? %>
      <div class="text-center"><%= link_to "ユーザー一覧", users_path, class: "btn btn-lg btn-primary" %></div>
    <% else %>
      <div class="text-center"><%= link_to "マイページ", user_url, class: "btn btn-lg btn-primary" %></div>
    <% end %>
  </div>
</div>

<script>
  const Peer = window.Peer;

  (async function main() {
    const localVideo = document.getElementById('js-local-stream');
    const joinTrigger = document.getElementById('js-join-trigger');
    const leaveTrigger = document.getElementById('js-leave-trigger');
    const remoteVideos = document.getElementById('js-remote-streams');
    const roomId = document.getElementById('js-room-id');
    const roomMode = document.getElementById('js-room-mode');
    const localText = document.getElementById('js-local-text');
    const sendTrigger = document.getElementById('js-send-trigger');
    const messages = document.getElementById('js-messages');
    const meta = document.getElementById('js-meta');
    const sdkSrc = document.querySelector('script[src*=skyway]');

    meta.innerText = `
      UA: ${navigator.userAgent}
      SDK: ${sdkSrc ? sdkSrc.src : 'unknown'}
    `.trim();

    const getRoomModeByHash = () => (location.hash === '#sfu' ? 'sfu' : 'mesh');

    roomMode.textContent = getRoomModeByHash();
    window.addEventListener(
      'hashchange',
      () => (roomMode.textContent = getRoomModeByHash())
    );

    const localStream = await navigator.mediaDevices
      .getUserMedia({
        audio: true,
        video: true,
      })
      .catch(console.error);

    // Render local stream
    localVideo.muted = true;
    localVideo.srcObject = localStream;
    localVideo.playsInline = true;
    localVideo.autoplay = true;
    await localVideo.play().catch(console.error);

    // eslint-disable-next-line require-atomic-updates
    const peer = (window.peer = new Peer({
      key: "56ce0219-dc92-4ccb-98e3-4fe9bc9be693",
      debug: 3,
    }));

    // Register join handler
    joinTrigger.addEventListener('click', () => {
      // Note that you need to ensure the peer has connected to signaling server
      // before using methods of peer instance.
      if (!peer.open) {
        return;
      }

      const room = peer.joinRoom(roomId.value, {
        mode: getRoomModeByHash(),
        stream: localStream,
      });

      room.once('open', () => {
        messages.textContent += '=== You joint ===\n';
      });
      room.on('peerJoin', peerId => {
        messages.textContent += `=== ${peerId} joined ===\n`;
      });

      // Render remote stream for new peer join in the room
      room.on('stream', async stream => {
        const newVideo = document.createElement('video');
        newVideo.srcObject = stream;
        newVideo.playsInline = true;
        // mark peerId to find it later at peerLeave event
        newVideo.setAttribute('data-peer-id', stream.peerId);
        remoteVideos.append(newVideo);
        await newVideo.play().catch(console.error);
      });

      room.on('data', ({ data, src }) => {
        // Show a message sent to the room and who sent
        messages.textContent += `${src}: ${data}\n`;
      });

      // for closing room members
      room.on('peerLeave', peerId => {
        const remoteVideo = remoteVideos.querySelector(
          `[data-peer-id="${peerId}"]`
        );
        remoteVideo.srcObject.getTracks().forEach(track => track.stop());
        remoteVideo.srcObject = null;
        remoteVideo.remove();

        messages.textContent += `=== ${peerId} left ===\n`;
      });

      // for closing myself
      room.once('close', () => {
        sendTrigger.removeEventListener('click', onClickSend);
        messages.textContent += '== You left ===\n';
        Array.from(remoteVideos.children).forEach(remoteVideo => {
          remoteVideo.srcObject.getTracks().forEach(track => track.stop());
          remoteVideo.srcObject = null;
          remoteVideo.remove();
        });
      });

      sendTrigger.addEventListener('click', onClickSend);
      leaveTrigger.addEventListener('click', () => room.close(), { once: true });

      function onClickSend() {
        // Send message to all of the peers in the room via websocket
        room.send(localText.value);

        messages.textContent += `${peer.id}: ${localText.value}\n`;
        localText.value = '';
      }
    });

    peer.on('error', console.error);
  })();
</script>